package apiserver

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func sortFields() []GithubSortField {
	return []GithubSortField{StarsField, IssuesField, ForksField, UpdatedField}
}

func TestBottomNRepos(t *testing.T) {
	expected := map[int]string{
		1: `[["Netflix/CassJMeter",162]]`,
		2: `[["Netflix/aws-autoscaling",1],["Netflix/servo",0]]`,
		3: `[["Netflix/gradle-template",107],["Netflix/aws-autoscaling",70],["Netflix/CassJMeter",70]]`,
		4: `[["Netflix/Priam","2023-03-15T23:39:59Z"],["Netflix/aws-autoscaling","2023-03-10T21:36:02Z"],["Netflix/astyanax","2023-03-09T06:04:22Z"],["Netflix/CassJMeter","2022-03-29T16:29:42Z"]]`,
	}

	for i, f := range sortFields() {
		r, e := BottomNRepos(repoData(), f, i+1)
		repoRes := string(r[:])
		assert.Equal(t, expected[i+1], repoRes, "results don't match")
		assert.Nil(t, e)
	}
}

func TestBottomNReposInputEdgeCases(t *testing.T) {
	r, e := BottomNRepos(repoData(), StarsField, 0)
	assert.Equal(t, []byte("[]"), r, "0 num should return []")
	assert.Nil(t, e)

	r, e = BottomNRepos(repoData(), StarsField, -1)
	assert.Equal(t, []byte("[]"), r, "negative num should return []")
	assert.Nil(t, e)

	r, e = BottomNRepos([]byte("[]"), StarsField, 1)
	assert.Equal(t, []byte("[]"), r, "Empty input gives empty output")
	assert.Nil(t, e)

	r, e = BottomNRepos(repoData(), StarsField, 200)
	assert.Equal(t, 11, strings.Count(string(r), "["), "requesting >num available returns all available")
	assert.Nil(t, e)
}

func repoData() []byte {
	return []byte(`[
  {
    "id": 2044029,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMDQ0MDI5",
    "name": "astyanax",
    "full_name": "Netflix/astyanax",
    "private": false,
    "owner": {
      "login": "Netflix",
      "id": 913567,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjkxMzU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/913567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Netflix",
      "html_url": "https://github.com/Netflix",
      "followers_url": "https://api.github.com/users/Netflix/followers",
      "following_url": "https://api.github.com/users/Netflix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Netflix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Netflix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Netflix/subscriptions",
      "organizations_url": "https://api.github.com/users/Netflix/orgs",
      "repos_url": "https://api.github.com/users/Netflix/repos",
      "events_url": "https://api.github.com/users/Netflix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Netflix/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Netflix/astyanax",
    "description": "Cassandra Java Client",
    "fork": false,
    "url": "https://api.github.com/repos/Netflix/astyanax",
    "forks_url": "https://api.github.com/repos/Netflix/astyanax/forks",
    "keys_url": "https://api.github.com/repos/Netflix/astyanax/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Netflix/astyanax/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Netflix/astyanax/teams",
    "hooks_url": "https://api.github.com/repos/Netflix/astyanax/hooks",
    "issue_events_url": "https://api.github.com/repos/Netflix/astyanax/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Netflix/astyanax/events",
    "assignees_url": "https://api.github.com/repos/Netflix/astyanax/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Netflix/astyanax/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Netflix/astyanax/tags",
    "blobs_url": "https://api.github.com/repos/Netflix/astyanax/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Netflix/astyanax/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Netflix/astyanax/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Netflix/astyanax/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Netflix/astyanax/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Netflix/astyanax/languages",
    "stargazers_url": "https://api.github.com/repos/Netflix/astyanax/stargazers",
    "contributors_url": "https://api.github.com/repos/Netflix/astyanax/contributors",
    "subscribers_url": "https://api.github.com/repos/Netflix/astyanax/subscribers",
    "subscription_url": "https://api.github.com/repos/Netflix/astyanax/subscription",
    "commits_url": "https://api.github.com/repos/Netflix/astyanax/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Netflix/astyanax/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Netflix/astyanax/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Netflix/astyanax/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Netflix/astyanax/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Netflix/astyanax/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Netflix/astyanax/merges",
    "archive_url": "https://api.github.com/repos/Netflix/astyanax/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Netflix/astyanax/downloads",
    "issues_url": "https://api.github.com/repos/Netflix/astyanax/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Netflix/astyanax/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Netflix/astyanax/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Netflix/astyanax/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Netflix/astyanax/labels{/name}",
    "releases_url": "https://api.github.com/repos/Netflix/astyanax/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Netflix/astyanax/deployments",
    "created_at": "2011-07-13T20:24:30Z",
    "updated_at": "2023-03-09T06:04:22Z",
    "pushed_at": "2023-03-24T09:13:14Z",
    "git_url": "git://github.com/Netflix/astyanax.git",
    "ssh_url": "git@github.com:Netflix/astyanax.git",
    "clone_url": "https://github.com/Netflix/astyanax.git",
    "svn_url": "https://github.com/Netflix/astyanax",
    "homepage": "",
    "size": 6987,
    "stargazers_count": 1027,
    "watchers_count": 1027,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 364,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 157,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 364,
    "open_issues": 157,
    "watchers": 1027,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    }
  },
  {
    "id": 2049379,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMDQ5Mzc5",
    "name": "curator",
    "full_name": "Netflix/curator",
    "private": false,
    "owner": {
      "login": "Netflix",
      "id": 913567,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjkxMzU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/913567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Netflix",
      "html_url": "https://github.com/Netflix",
      "followers_url": "https://api.github.com/users/Netflix/followers",
      "following_url": "https://api.github.com/users/Netflix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Netflix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Netflix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Netflix/subscriptions",
      "organizations_url": "https://api.github.com/users/Netflix/orgs",
      "repos_url": "https://api.github.com/users/Netflix/repos",
      "events_url": "https://api.github.com/users/Netflix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Netflix/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Netflix/curator",
    "description": "ZooKeeper client wrapper and rich ZooKeeper framework",
    "fork": false,
    "url": "https://api.github.com/repos/Netflix/curator",
    "forks_url": "https://api.github.com/repos/Netflix/curator/forks",
    "keys_url": "https://api.github.com/repos/Netflix/curator/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Netflix/curator/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Netflix/curator/teams",
    "hooks_url": "https://api.github.com/repos/Netflix/curator/hooks",
    "issue_events_url": "https://api.github.com/repos/Netflix/curator/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Netflix/curator/events",
    "assignees_url": "https://api.github.com/repos/Netflix/curator/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Netflix/curator/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Netflix/curator/tags",
    "blobs_url": "https://api.github.com/repos/Netflix/curator/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Netflix/curator/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Netflix/curator/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Netflix/curator/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Netflix/curator/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Netflix/curator/languages",
    "stargazers_url": "https://api.github.com/repos/Netflix/curator/stargazers",
    "contributors_url": "https://api.github.com/repos/Netflix/curator/contributors",
    "subscribers_url": "https://api.github.com/repos/Netflix/curator/subscribers",
    "subscription_url": "https://api.github.com/repos/Netflix/curator/subscription",
    "commits_url": "https://api.github.com/repos/Netflix/curator/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Netflix/curator/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Netflix/curator/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Netflix/curator/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Netflix/curator/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Netflix/curator/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Netflix/curator/merges",
    "archive_url": "https://api.github.com/repos/Netflix/curator/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Netflix/curator/downloads",
    "issues_url": "https://api.github.com/repos/Netflix/curator/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Netflix/curator/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Netflix/curator/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Netflix/curator/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Netflix/curator/labels{/name}",
    "releases_url": "https://api.github.com/repos/Netflix/curator/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Netflix/curator/deployments",
    "created_at": "2011-07-14T19:47:55Z",
    "updated_at": "2023-04-06T03:22:29Z",
    "pushed_at": "2023-03-24T09:35:04Z",
    "git_url": "git://github.com/Netflix/curator.git",
    "ssh_url": "git@github.com:Netflix/curator.git",
    "clone_url": "https://github.com/Netflix/curator.git",
    "svn_url": "https://github.com/Netflix/curator",
    "homepage": "http://netflix.github.com/curator",
    "size": 7545,
    "stargazers_count": 2138,
    "watchers_count": 2138,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 444,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 12,
    "license": {
      "key": "other",
      "name": "Other",
      "spdx_id": "NOASSERTION",
      "url": null,
      "node_id": "MDc6TGljZW5zZTA="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 444,
    "open_issues": 12,
    "watchers": 2138,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    }
  },
  {
    "id": 2079469,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMDc5NDY5",
    "name": "Priam",
    "full_name": "Netflix/Priam",
    "private": false,
    "owner": {
      "login": "Netflix",
      "id": 913567,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjkxMzU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/913567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Netflix",
      "html_url": "https://github.com/Netflix",
      "followers_url": "https://api.github.com/users/Netflix/followers",
      "following_url": "https://api.github.com/users/Netflix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Netflix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Netflix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Netflix/subscriptions",
      "organizations_url": "https://api.github.com/users/Netflix/orgs",
      "repos_url": "https://api.github.com/users/Netflix/repos",
      "events_url": "https://api.github.com/users/Netflix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Netflix/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Netflix/Priam",
    "description": "Co-Process for backup/recovery, Token Management, and Centralized Configuration management for Cassandra.",
    "fork": false,
    "url": "https://api.github.com/repos/Netflix/Priam",
    "forks_url": "https://api.github.com/repos/Netflix/Priam/forks",
    "keys_url": "https://api.github.com/repos/Netflix/Priam/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Netflix/Priam/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Netflix/Priam/teams",
    "hooks_url": "https://api.github.com/repos/Netflix/Priam/hooks",
    "issue_events_url": "https://api.github.com/repos/Netflix/Priam/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Netflix/Priam/events",
    "assignees_url": "https://api.github.com/repos/Netflix/Priam/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Netflix/Priam/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Netflix/Priam/tags",
    "blobs_url": "https://api.github.com/repos/Netflix/Priam/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Netflix/Priam/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Netflix/Priam/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Netflix/Priam/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Netflix/Priam/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Netflix/Priam/languages",
    "stargazers_url": "https://api.github.com/repos/Netflix/Priam/stargazers",
    "contributors_url": "https://api.github.com/repos/Netflix/Priam/contributors",
    "subscribers_url": "https://api.github.com/repos/Netflix/Priam/subscribers",
    "subscription_url": "https://api.github.com/repos/Netflix/Priam/subscription",
    "commits_url": "https://api.github.com/repos/Netflix/Priam/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Netflix/Priam/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Netflix/Priam/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Netflix/Priam/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Netflix/Priam/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Netflix/Priam/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Netflix/Priam/merges",
    "archive_url": "https://api.github.com/repos/Netflix/Priam/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Netflix/Priam/downloads",
    "issues_url": "https://api.github.com/repos/Netflix/Priam/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Netflix/Priam/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Netflix/Priam/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Netflix/Priam/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Netflix/Priam/labels{/name}",
    "releases_url": "https://api.github.com/repos/Netflix/Priam/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Netflix/Priam/deployments",
    "created_at": "2011-07-20T17:51:25Z",
    "updated_at": "2023-03-15T23:39:59Z",
    "pushed_at": "2023-04-04T03:30:56Z",
    "git_url": "git://github.com/Netflix/Priam.git",
    "ssh_url": "git@github.com:Netflix/Priam.git",
    "clone_url": "https://github.com/Netflix/Priam.git",
    "svn_url": "https://github.com/Netflix/Priam",
    "homepage": "",
    "size": 13619,
    "stargazers_count": 1024,
    "watchers_count": 1024,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 296,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 48,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 296,
    "open_issues": 48,
    "watchers": 1024,
    "default_branch": "3.x",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    }
  },
  {
    "id": 2614362,
    "node_id": "MDEwOlJlcG9zaXRvcnkyNjE0MzYy",
    "name": "CassJMeter",
    "full_name": "Netflix/CassJMeter",
    "private": false,
    "owner": {
      "login": "Netflix",
      "id": 913567,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjkxMzU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/913567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Netflix",
      "html_url": "https://github.com/Netflix",
      "followers_url": "https://api.github.com/users/Netflix/followers",
      "following_url": "https://api.github.com/users/Netflix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Netflix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Netflix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Netflix/subscriptions",
      "organizations_url": "https://api.github.com/users/Netflix/orgs",
      "repos_url": "https://api.github.com/users/Netflix/repos",
      "events_url": "https://api.github.com/users/Netflix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Netflix/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Netflix/CassJMeter",
    "description": "JMeter plugin to run cassandra tests.",
    "fork": false,
    "url": "https://api.github.com/repos/Netflix/CassJMeter",
    "forks_url": "https://api.github.com/repos/Netflix/CassJMeter/forks",
    "keys_url": "https://api.github.com/repos/Netflix/CassJMeter/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Netflix/CassJMeter/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Netflix/CassJMeter/teams",
    "hooks_url": "https://api.github.com/repos/Netflix/CassJMeter/hooks",
    "issue_events_url": "https://api.github.com/repos/Netflix/CassJMeter/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Netflix/CassJMeter/events",
    "assignees_url": "https://api.github.com/repos/Netflix/CassJMeter/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Netflix/CassJMeter/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Netflix/CassJMeter/tags",
    "blobs_url": "https://api.github.com/repos/Netflix/CassJMeter/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Netflix/CassJMeter/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Netflix/CassJMeter/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Netflix/CassJMeter/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Netflix/CassJMeter/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Netflix/CassJMeter/languages",
    "stargazers_url": "https://api.github.com/repos/Netflix/CassJMeter/stargazers",
    "contributors_url": "https://api.github.com/repos/Netflix/CassJMeter/contributors",
    "subscribers_url": "https://api.github.com/repos/Netflix/CassJMeter/subscribers",
    "subscription_url": "https://api.github.com/repos/Netflix/CassJMeter/subscription",
    "commits_url": "https://api.github.com/repos/Netflix/CassJMeter/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Netflix/CassJMeter/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Netflix/CassJMeter/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Netflix/CassJMeter/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Netflix/CassJMeter/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Netflix/CassJMeter/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Netflix/CassJMeter/merges",
    "archive_url": "https://api.github.com/repos/Netflix/CassJMeter/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Netflix/CassJMeter/downloads",
    "issues_url": "https://api.github.com/repos/Netflix/CassJMeter/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Netflix/CassJMeter/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Netflix/CassJMeter/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Netflix/CassJMeter/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Netflix/CassJMeter/labels{/name}",
    "releases_url": "https://api.github.com/repos/Netflix/CassJMeter/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Netflix/CassJMeter/deployments",
    "created_at": "2011-10-20T16:18:00Z",
    "updated_at": "2022-03-29T16:29:42Z",
    "pushed_at": "2023-03-24T09:53:54Z",
    "git_url": "git://github.com/Netflix/CassJMeter.git",
    "ssh_url": "git@github.com:Netflix/CassJMeter.git",
    "clone_url": "https://github.com/Netflix/CassJMeter.git",
    "svn_url": "https://github.com/Netflix/CassJMeter",
    "homepage": "",
    "size": 2441,
    "stargazers_count": 162,
    "watchers_count": 162,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 70,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 16,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 70,
    "open_issues": 16,
    "watchers": 162,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    }
  },
  {
    "id": 2997701,
    "node_id": "MDEwOlJlcG9zaXRvcnkyOTk3NzAx",
    "name": "servo",
    "full_name": "Netflix/servo",
    "private": false,
    "owner": {
      "login": "Netflix",
      "id": 913567,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjkxMzU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/913567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Netflix",
      "html_url": "https://github.com/Netflix",
      "followers_url": "https://api.github.com/users/Netflix/followers",
      "following_url": "https://api.github.com/users/Netflix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Netflix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Netflix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Netflix/subscriptions",
      "organizations_url": "https://api.github.com/users/Netflix/orgs",
      "repos_url": "https://api.github.com/users/Netflix/repos",
      "events_url": "https://api.github.com/users/Netflix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Netflix/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Netflix/servo",
    "description": "Netflix Application Monitoring Library",
    "fork": false,
    "url": "https://api.github.com/repos/Netflix/servo",
    "forks_url": "https://api.github.com/repos/Netflix/servo/forks",
    "keys_url": "https://api.github.com/repos/Netflix/servo/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Netflix/servo/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Netflix/servo/teams",
    "hooks_url": "https://api.github.com/repos/Netflix/servo/hooks",
    "issue_events_url": "https://api.github.com/repos/Netflix/servo/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Netflix/servo/events",
    "assignees_url": "https://api.github.com/repos/Netflix/servo/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Netflix/servo/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Netflix/servo/tags",
    "blobs_url": "https://api.github.com/repos/Netflix/servo/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Netflix/servo/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Netflix/servo/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Netflix/servo/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Netflix/servo/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Netflix/servo/languages",
    "stargazers_url": "https://api.github.com/repos/Netflix/servo/stargazers",
    "contributors_url": "https://api.github.com/repos/Netflix/servo/contributors",
    "subscribers_url": "https://api.github.com/repos/Netflix/servo/subscribers",
    "subscription_url": "https://api.github.com/repos/Netflix/servo/subscription",
    "commits_url": "https://api.github.com/repos/Netflix/servo/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Netflix/servo/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Netflix/servo/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Netflix/servo/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Netflix/servo/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Netflix/servo/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Netflix/servo/merges",
    "archive_url": "https://api.github.com/repos/Netflix/servo/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Netflix/servo/downloads",
    "issues_url": "https://api.github.com/repos/Netflix/servo/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Netflix/servo/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Netflix/servo/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Netflix/servo/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Netflix/servo/labels{/name}",
    "releases_url": "https://api.github.com/repos/Netflix/servo/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Netflix/servo/deployments",
    "created_at": "2011-12-16T21:09:27Z",
    "updated_at": "2023-03-31T17:14:58Z",
    "pushed_at": "2023-03-27T15:54:14Z",
    "git_url": "git://github.com/Netflix/servo.git",
    "ssh_url": "git@github.com:Netflix/servo.git",
    "clone_url": "https://github.com/Netflix/servo.git",
    "svn_url": "https://github.com/Netflix/servo",
    "homepage": "",
    "size": 5422,
    "stargazers_count": 1383,
    "watchers_count": 1383,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 298,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 298,
    "open_issues": 0,
    "watchers": 1383,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    }
  },
  {
    "id": 3157953,
    "node_id": "MDEwOlJlcG9zaXRvcnkzMTU3OTUz",
    "name": "aws-autoscaling",
    "full_name": "Netflix/aws-autoscaling",
    "private": false,
    "owner": {
      "login": "Netflix",
      "id": 913567,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjkxMzU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/913567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Netflix",
      "html_url": "https://github.com/Netflix",
      "followers_url": "https://api.github.com/users/Netflix/followers",
      "following_url": "https://api.github.com/users/Netflix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Netflix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Netflix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Netflix/subscriptions",
      "organizations_url": "https://api.github.com/users/Netflix/orgs",
      "repos_url": "https://api.github.com/users/Netflix/repos",
      "events_url": "https://api.github.com/users/Netflix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Netflix/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Netflix/aws-autoscaling",
    "description": "Tools and Documentation about using Auto Scaling",
    "fork": false,
    "url": "https://api.github.com/repos/Netflix/aws-autoscaling",
    "forks_url": "https://api.github.com/repos/Netflix/aws-autoscaling/forks",
    "keys_url": "https://api.github.com/repos/Netflix/aws-autoscaling/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Netflix/aws-autoscaling/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Netflix/aws-autoscaling/teams",
    "hooks_url": "https://api.github.com/repos/Netflix/aws-autoscaling/hooks",
    "issue_events_url": "https://api.github.com/repos/Netflix/aws-autoscaling/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Netflix/aws-autoscaling/events",
    "assignees_url": "https://api.github.com/repos/Netflix/aws-autoscaling/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Netflix/aws-autoscaling/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Netflix/aws-autoscaling/tags",
    "blobs_url": "https://api.github.com/repos/Netflix/aws-autoscaling/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Netflix/aws-autoscaling/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Netflix/aws-autoscaling/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Netflix/aws-autoscaling/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Netflix/aws-autoscaling/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Netflix/aws-autoscaling/languages",
    "stargazers_url": "https://api.github.com/repos/Netflix/aws-autoscaling/stargazers",
    "contributors_url": "https://api.github.com/repos/Netflix/aws-autoscaling/contributors",
    "subscribers_url": "https://api.github.com/repos/Netflix/aws-autoscaling/subscribers",
    "subscription_url": "https://api.github.com/repos/Netflix/aws-autoscaling/subscription",
    "commits_url": "https://api.github.com/repos/Netflix/aws-autoscaling/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Netflix/aws-autoscaling/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Netflix/aws-autoscaling/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Netflix/aws-autoscaling/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Netflix/aws-autoscaling/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Netflix/aws-autoscaling/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Netflix/aws-autoscaling/merges",
    "archive_url": "https://api.github.com/repos/Netflix/aws-autoscaling/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Netflix/aws-autoscaling/downloads",
    "issues_url": "https://api.github.com/repos/Netflix/aws-autoscaling/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Netflix/aws-autoscaling/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Netflix/aws-autoscaling/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Netflix/aws-autoscaling/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Netflix/aws-autoscaling/labels{/name}",
    "releases_url": "https://api.github.com/repos/Netflix/aws-autoscaling/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Netflix/aws-autoscaling/deployments",
    "created_at": "2012-01-11T22:29:55Z",
    "updated_at": "2023-03-10T21:36:02Z",
    "pushed_at": "2015-12-12T00:23:13Z",
    "git_url": "git://github.com/Netflix/aws-autoscaling.git",
    "ssh_url": "git@github.com:Netflix/aws-autoscaling.git",
    "clone_url": "https://github.com/Netflix/aws-autoscaling.git",
    "svn_url": "https://github.com/Netflix/aws-autoscaling",
    "homepage": "https://github.com/Netflix/aws-autoscaling/wiki",
    "size": 17,
    "stargazers_count": 426,
    "watchers_count": 426,
    "language": "Shell",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 70,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 1,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 95,
    "open_issues": 1,
    "watchers": 426,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    }
  },
  {
    "id": 3310609,
    "node_id": "MDEwOlJlcG9zaXRvcnkzMzEwNjA5",
    "name": "netflix.github.com",
    "full_name": "Netflix/netflix.github.com",
    "private": false,
    "owner": {
      "login": "Netflix",
      "id": 913567,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjkxMzU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/913567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Netflix",
      "html_url": "https://github.com/Netflix",
      "followers_url": "https://api.github.com/users/Netflix/followers",
      "following_url": "https://api.github.com/users/Netflix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Netflix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Netflix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Netflix/subscriptions",
      "organizations_url": "https://api.github.com/users/Netflix/orgs",
      "repos_url": "https://api.github.com/users/Netflix/repos",
      "events_url": "https://api.github.com/users/Netflix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Netflix/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Netflix/netflix.github.com",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Netflix/netflix.github.com",
    "forks_url": "https://api.github.com/repos/Netflix/netflix.github.com/forks",
    "keys_url": "https://api.github.com/repos/Netflix/netflix.github.com/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Netflix/netflix.github.com/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Netflix/netflix.github.com/teams",
    "hooks_url": "https://api.github.com/repos/Netflix/netflix.github.com/hooks",
    "issue_events_url": "https://api.github.com/repos/Netflix/netflix.github.com/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Netflix/netflix.github.com/events",
    "assignees_url": "https://api.github.com/repos/Netflix/netflix.github.com/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Netflix/netflix.github.com/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Netflix/netflix.github.com/tags",
    "blobs_url": "https://api.github.com/repos/Netflix/netflix.github.com/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Netflix/netflix.github.com/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Netflix/netflix.github.com/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Netflix/netflix.github.com/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Netflix/netflix.github.com/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Netflix/netflix.github.com/languages",
    "stargazers_url": "https://api.github.com/repos/Netflix/netflix.github.com/stargazers",
    "contributors_url": "https://api.github.com/repos/Netflix/netflix.github.com/contributors",
    "subscribers_url": "https://api.github.com/repos/Netflix/netflix.github.com/subscribers",
    "subscription_url": "https://api.github.com/repos/Netflix/netflix.github.com/subscription",
    "commits_url": "https://api.github.com/repos/Netflix/netflix.github.com/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Netflix/netflix.github.com/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Netflix/netflix.github.com/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Netflix/netflix.github.com/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Netflix/netflix.github.com/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Netflix/netflix.github.com/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Netflix/netflix.github.com/merges",
    "archive_url": "https://api.github.com/repos/Netflix/netflix.github.com/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Netflix/netflix.github.com/downloads",
    "issues_url": "https://api.github.com/repos/Netflix/netflix.github.com/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Netflix/netflix.github.com/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Netflix/netflix.github.com/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Netflix/netflix.github.com/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Netflix/netflix.github.com/labels{/name}",
    "releases_url": "https://api.github.com/repos/Netflix/netflix.github.com/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Netflix/netflix.github.com/deployments",
    "created_at": "2012-01-31T00:50:10Z",
    "updated_at": "2023-04-05T08:48:59Z",
    "pushed_at": "2023-02-22T18:41:05Z",
    "git_url": "git://github.com/Netflix/netflix.github.com.git",
    "ssh_url": "git@github.com:Netflix/netflix.github.com.git",
    "clone_url": "https://github.com/Netflix/netflix.github.com.git",
    "svn_url": "https://github.com/Netflix/netflix.github.com",
    "homepage": "",
    "size": 26541,
    "stargazers_count": 1352,
    "watchers_count": 1352,
    "language": "HTML",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 440,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 37,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 440,
    "open_issues": 37,
    "watchers": 1352,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    }
  },
  {
    "id": 3701319,
    "node_id": "MDEwOlJlcG9zaXRvcnkzNzAxMzE5",
    "name": "gradle-template",
    "full_name": "Netflix/gradle-template",
    "private": false,
    "owner": {
      "login": "Netflix",
      "id": 913567,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjkxMzU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/913567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Netflix",
      "html_url": "https://github.com/Netflix",
      "followers_url": "https://api.github.com/users/Netflix/followers",
      "following_url": "https://api.github.com/users/Netflix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Netflix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Netflix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Netflix/subscriptions",
      "organizations_url": "https://api.github.com/users/Netflix/orgs",
      "repos_url": "https://api.github.com/users/Netflix/repos",
      "events_url": "https://api.github.com/users/Netflix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Netflix/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Netflix/gradle-template",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/Netflix/gradle-template",
    "forks_url": "https://api.github.com/repos/Netflix/gradle-template/forks",
    "keys_url": "https://api.github.com/repos/Netflix/gradle-template/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Netflix/gradle-template/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Netflix/gradle-template/teams",
    "hooks_url": "https://api.github.com/repos/Netflix/gradle-template/hooks",
    "issue_events_url": "https://api.github.com/repos/Netflix/gradle-template/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Netflix/gradle-template/events",
    "assignees_url": "https://api.github.com/repos/Netflix/gradle-template/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Netflix/gradle-template/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Netflix/gradle-template/tags",
    "blobs_url": "https://api.github.com/repos/Netflix/gradle-template/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Netflix/gradle-template/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Netflix/gradle-template/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Netflix/gradle-template/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Netflix/gradle-template/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Netflix/gradle-template/languages",
    "stargazers_url": "https://api.github.com/repos/Netflix/gradle-template/stargazers",
    "contributors_url": "https://api.github.com/repos/Netflix/gradle-template/contributors",
    "subscribers_url": "https://api.github.com/repos/Netflix/gradle-template/subscribers",
    "subscription_url": "https://api.github.com/repos/Netflix/gradle-template/subscription",
    "commits_url": "https://api.github.com/repos/Netflix/gradle-template/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Netflix/gradle-template/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Netflix/gradle-template/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Netflix/gradle-template/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Netflix/gradle-template/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Netflix/gradle-template/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Netflix/gradle-template/merges",
    "archive_url": "https://api.github.com/repos/Netflix/gradle-template/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Netflix/gradle-template/downloads",
    "issues_url": "https://api.github.com/repos/Netflix/gradle-template/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Netflix/gradle-template/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Netflix/gradle-template/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Netflix/gradle-template/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Netflix/gradle-template/labels{/name}",
    "releases_url": "https://api.github.com/repos/Netflix/gradle-template/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Netflix/gradle-template/deployments",
    "created_at": "2012-03-12T23:34:43Z",
    "updated_at": "2023-04-02T23:43:54Z",
    "pushed_at": "2023-03-24T09:26:03Z",
    "git_url": "git://github.com/Netflix/gradle-template.git",
    "ssh_url": "git@github.com:Netflix/gradle-template.git",
    "clone_url": "https://github.com/Netflix/gradle-template.git",
    "svn_url": "https://github.com/Netflix/gradle-template",
    "homepage": "",
    "size": 679,
    "stargazers_count": 245,
    "watchers_count": 245,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 107,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 3,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 107,
    "open_issues": 3,
    "watchers": 245,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    }
  },
  {
    "id": 4291387,
    "node_id": "MDEwOlJlcG9zaXRvcnk0MjkxMzg3",
    "name": "archaius",
    "full_name": "Netflix/archaius",
    "private": false,
    "owner": {
      "login": "Netflix",
      "id": 913567,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjkxMzU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/913567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Netflix",
      "html_url": "https://github.com/Netflix",
      "followers_url": "https://api.github.com/users/Netflix/followers",
      "following_url": "https://api.github.com/users/Netflix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Netflix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Netflix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Netflix/subscriptions",
      "organizations_url": "https://api.github.com/users/Netflix/orgs",
      "repos_url": "https://api.github.com/users/Netflix/repos",
      "events_url": "https://api.github.com/users/Netflix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Netflix/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Netflix/archaius",
    "description": "Library for configuration management API",
    "fork": false,
    "url": "https://api.github.com/repos/Netflix/archaius",
    "forks_url": "https://api.github.com/repos/Netflix/archaius/forks",
    "keys_url": "https://api.github.com/repos/Netflix/archaius/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Netflix/archaius/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Netflix/archaius/teams",
    "hooks_url": "https://api.github.com/repos/Netflix/archaius/hooks",
    "issue_events_url": "https://api.github.com/repos/Netflix/archaius/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Netflix/archaius/events",
    "assignees_url": "https://api.github.com/repos/Netflix/archaius/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Netflix/archaius/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Netflix/archaius/tags",
    "blobs_url": "https://api.github.com/repos/Netflix/archaius/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Netflix/archaius/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Netflix/archaius/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Netflix/archaius/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Netflix/archaius/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Netflix/archaius/languages",
    "stargazers_url": "https://api.github.com/repos/Netflix/archaius/stargazers",
    "contributors_url": "https://api.github.com/repos/Netflix/archaius/contributors",
    "subscribers_url": "https://api.github.com/repos/Netflix/archaius/subscribers",
    "subscription_url": "https://api.github.com/repos/Netflix/archaius/subscription",
    "commits_url": "https://api.github.com/repos/Netflix/archaius/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Netflix/archaius/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Netflix/archaius/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Netflix/archaius/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Netflix/archaius/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Netflix/archaius/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Netflix/archaius/merges",
    "archive_url": "https://api.github.com/repos/Netflix/archaius/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Netflix/archaius/downloads",
    "issues_url": "https://api.github.com/repos/Netflix/archaius/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Netflix/archaius/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Netflix/archaius/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Netflix/archaius/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Netflix/archaius/labels{/name}",
    "releases_url": "https://api.github.com/repos/Netflix/archaius/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Netflix/archaius/deployments",
    "created_at": "2012-05-11T00:07:05Z",
    "updated_at": "2023-04-06T15:45:37Z",
    "pushed_at": "2023-04-01T19:24:26Z",
    "git_url": "git://github.com/Netflix/archaius.git",
    "ssh_url": "git@github.com:Netflix/archaius.git",
    "clone_url": "https://github.com/Netflix/archaius.git",
    "svn_url": "https://github.com/Netflix/archaius",
    "homepage": "",
    "size": 3509,
    "stargazers_count": 2397,
    "watchers_count": 2397,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 485,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 47,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 485,
    "open_issues": 47,
    "watchers": 2397,
    "default_branch": "2.x",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    }
  },
  {
    "id": 4398942,
    "node_id": "MDEwOlJlcG9zaXRvcnk0Mzk4OTQy",
    "name": "asgard",
    "full_name": "Netflix/asgard",
    "private": false,
    "owner": {
      "login": "Netflix",
      "id": 913567,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjkxMzU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/913567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Netflix",
      "html_url": "https://github.com/Netflix",
      "followers_url": "https://api.github.com/users/Netflix/followers",
      "following_url": "https://api.github.com/users/Netflix/following{/other_user}",
      "gists_url": "https://api.github.com/users/Netflix/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Netflix/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Netflix/subscriptions",
      "organizations_url": "https://api.github.com/users/Netflix/orgs",
      "repos_url": "https://api.github.com/users/Netflix/repos",
      "events_url": "https://api.github.com/users/Netflix/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Netflix/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/Netflix/asgard",
    "description": "[Asgard is deprecated at Netflix. We use Spinnaker ( www.spinnaker.io ).] Web interface for application deployments and cloud management in Amazon Web Services (AWS). Binary download: http://github.com/Netflix/asgard/releases",
    "fork": false,
    "url": "https://api.github.com/repos/Netflix/asgard",
    "forks_url": "https://api.github.com/repos/Netflix/asgard/forks",
    "keys_url": "https://api.github.com/repos/Netflix/asgard/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/Netflix/asgard/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/Netflix/asgard/teams",
    "hooks_url": "https://api.github.com/repos/Netflix/asgard/hooks",
    "issue_events_url": "https://api.github.com/repos/Netflix/asgard/issues/events{/number}",
    "events_url": "https://api.github.com/repos/Netflix/asgard/events",
    "assignees_url": "https://api.github.com/repos/Netflix/asgard/assignees{/user}",
    "branches_url": "https://api.github.com/repos/Netflix/asgard/branches{/branch}",
    "tags_url": "https://api.github.com/repos/Netflix/asgard/tags",
    "blobs_url": "https://api.github.com/repos/Netflix/asgard/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/Netflix/asgard/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/Netflix/asgard/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/Netflix/asgard/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/Netflix/asgard/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/Netflix/asgard/languages",
    "stargazers_url": "https://api.github.com/repos/Netflix/asgard/stargazers",
    "contributors_url": "https://api.github.com/repos/Netflix/asgard/contributors",
    "subscribers_url": "https://api.github.com/repos/Netflix/asgard/subscribers",
    "subscription_url": "https://api.github.com/repos/Netflix/asgard/subscription",
    "commits_url": "https://api.github.com/repos/Netflix/asgard/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/Netflix/asgard/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/Netflix/asgard/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/Netflix/asgard/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/Netflix/asgard/contents/{+path}",
    "compare_url": "https://api.github.com/repos/Netflix/asgard/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/Netflix/asgard/merges",
    "archive_url": "https://api.github.com/repos/Netflix/asgard/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/Netflix/asgard/downloads",
    "issues_url": "https://api.github.com/repos/Netflix/asgard/issues{/number}",
    "pulls_url": "https://api.github.com/repos/Netflix/asgard/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/Netflix/asgard/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/Netflix/asgard/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/Netflix/asgard/labels{/name}",
    "releases_url": "https://api.github.com/repos/Netflix/asgard/releases{/id}",
    "deployments_url": "https://api.github.com/repos/Netflix/asgard/deployments",
    "created_at": "2012-05-21T21:24:15Z",
    "updated_at": "2023-03-21T06:44:02Z",
    "pushed_at": "2023-03-24T09:41:00Z",
    "git_url": "git://github.com/Netflix/asgard.git",
    "ssh_url": "git@github.com:Netflix/asgard.git",
    "clone_url": "https://github.com/Netflix/asgard.git",
    "svn_url": "https://github.com/Netflix/asgard",
    "homepage": "http://netflix.github.com/asgard",
    "size": 26590,
    "stargazers_count": 2235,
    "watchers_count": 2235,
    "language": "Groovy",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 434,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 102,
    "license": {
      "key": "apache-2.0",
      "name": "Apache License 2.0",
      "spdx_id": "Apache-2.0",
      "url": "https://api.github.com/licenses/apache-2.0",
      "node_id": "MDc6TGljZW5zZTI="
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 434,
    "open_issues": 102,
    "watchers": 2235,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "maintain": false,
      "push": false,
      "triage": false,
      "pull": true
    }
  }
]`)
}
